image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - deploy

pytest:
  stage: test
  image: python:3.6-slim-stretch
  before_script:
    - apt-get update
    - apt-get install --no-install-recommends -q -y libsnmp-dev build-essential git
    - pip install --no-cache-dir pipenv
    - pipenv install --dev
    - docker run -d --net=host -p 127.0.0.1:6379:6379 --name redis redis:5-alpine
  script:
    - export REDIS_HOST="127.0.0.1"
    - pipenv run pytest -x test_snmpcollector.py
  after_script:
    - docker rm -f redis

deploy to docker hub:
  stage: deploy
  when: manual
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]+[.][0-9]+[.][0-9]+([.][^.]+)?$/
  variables:
    CI_REGISTRY_IMAGE: grafolean/grafolean-collector-snmp
  script:
    - apk add --no-cache git
    # check that we are deploying the latest version:
    - export LAST_KNOWN_VERSION=`git tag -l --sort=-version:refname "v*.*.*" | head -n 1 | tr -d '[:space:]'`
    - '[ "$LAST_KNOWN_VERSION" == "$CI_COMMIT_TAG" ] || (echo "Tag does not denote latest known version (which is $LAST_KNOWN_VERSION), aborting!" && exit 1)'
    - echo "Deploying..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "docker.io/$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" -t "docker.io/$CI_REGISTRY_IMAGE:latest" --build-arg VERSION=$CI_COMMIT_TAG --build-arg VCS_REF=$CI_COMMIT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') .
    - docker push "docker.io/$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push "docker.io/$CI_REGISTRY_IMAGE:latest"
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker rmi $CI_REGISTRY_IMAGE:latest
