version: '2.1'
services:

  #
  # Welcome to Grafolean SNMP Collector!
  #
  # This file should be modified to suit your running environment. Please check the comments and change
  # the settings appropriately.
  #

  snmpcollector:
    # If you wish to load an explicit version, change the next line. For example:
    #   image: grafolean/grafolean-collector-snmp:v1.0.0
    image: grafolean/grafolean-collector-snmp
    container_name: grafolean-collector-snmp
    environment:
      # Backend url must be set to the address of the Grafolean backend, for example this uses Grafolean hosted service:
      # - BACKEND_URL=https://grafolean.com/api
      # IMPORTANT: '127.0.0.1' and 'localhost' are _never_ correct addresses for Grafolean backend, because they translate
      # to container, not host.
      - BACKEND_URL=
      # To use SNMP Collector, a bot with the protocol "snmp" must be added via user interface, then the token needs to be copied here:
      - BOT_TOKEN=
      # Interval between fetching information about jobs:
      - JOBS_REFRESH_INTERVAL=60
      - REDIS_HOST=redis
    restart: always

  redis:
    image: redis:5-alpine
    container_name: grafolean-collector-snmp-redis
