version: '2.1'
services:

  #
  # Welcome to Grafolean SNMP Collector!
  #
  # This file is meant for development purposes only. Please use `docker-compose.yml` for usual installation.
  #
  # Feel free to investigate this file (and comments), but the preferred way of changing development settings is to:
  # - copy .env.example to .env (which is already in .gitignore)
  # - change the settings in .env
  #

  snmpcollector:
    # If you wish to load an explicit version, change the next line. For example:
    #   image: grafolean/grafolean-collector-snmp:v1.0.0
    image: grafolean/grafolean-collector-snmp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafolean-collector-snmp
    environment:
      # Backend url must be set to the address of the Grafolean backend, for example this uses Grafolean hosted service:
      # - BACKEND_URL=https://grafolean.com/api
      - BACKEND_URL=${BACKEND_URL}
      # To use SNMP Collector, a bot with the protocol "snmp" must be added via user interface, then the token needs to be copied here:
      - BOT_TOKEN=${BOT_TOKEN}
      # Interval between fetching information about jobs:
      - JOBS_REFRESH_INTERVAL=${JOBS_REFRESH_INTERVAL}
    # Grafolean backend must be accessible on BACKEND_URL *from the point of view of container*. If running
    # on the same host, '127.0.0.1' translates to container, not host - this directive changes network mode
    # so that Docker networking is bypassed.
    network_mode: "host"


  redis:
    image: redis:5-alpine
    container_name: grafolean-collector-snmp-redis
    ports:
      - "6379:6379"
    # We advise not to use `network_mode: "host"` in production, because it would expose Redis to the network.
    network_mode: "host"


  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal-snmp
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
